// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMS.Models;

public partial class Answer
{
    [Key]
    [Column("AnswerID")]
    public int AnswerId { get; set; }

    [Required]
    public string Answercontent { get; set; }

    public bool IdelAnswer { get; set; }

    [Column("QuestionID")]
    public int QuestionId { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Answers")]
    public virtual Question Question { get; set; }
}