// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EMS.Models;

public partial class EMSDBContext : DbContext
{
    public EMSDBContext()
    {
    }

    public EMSDBContext(DbContextOptions<EMSDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        { 
         optionsBuilder.UseSqlServer(@"Data Source=DESKTOP-MMBMKTC\MSSQLDEV;Initial Catalog=EMSDB;Persist Security Info=True;User ID=sa;Password=DB@dmin;TrustServerCertificate=True");
        }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Question>(entity =>
        {
            entity.Property(e => e.QuestionType).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}