// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMS.Models;

public partial class Exam
{
    [Key]
    [Column("ExamID")]
    [StringLength(50)]
    public string ExamId { get; set; }

    [StringLength(50)]
    public string ExamName { get; set; }

    public byte? ExamTime { get; set; }

    public byte? ExamMarke { get; set; }

    [Column("Min_Marke")]
    public byte? MinMarke { get; set; }

    [InverseProperty("Exam")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}