// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EMS.Models;

public partial class Question
{
    [Key]
    [Column("QuestionID")]
    public int QuestionId { get; set; }

    [Column("ExamID")]
    [StringLength(50)]
    [Display(Name = "E.ID")]
    public string ExamId { get; set; }
    [Display(Name = "Q.Content")]
    public string QuestionContent { get; set; }

    [StringLength(10)]
    [Display(Name = "Q.Type")]
    public string QuestionType { get; set; }
    [Display(Name = "Q.Mark")]
    public byte? QuestionMark { get; set; }
    [Display(Name = "No.Answers")]
    public byte? NumberOfAnswers { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [ForeignKey("ExamId")]
    [InverseProperty("Questions")]
    public virtual Exam Exam { get; set; }
}